# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-11-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=100, null=True)),
                ('stupid_count', models.IntegerField(default=0)),
                ('fat_count', models.IntegerField(default=0)),
                ('dumb_count', models.IntegerField(default=0)),
            ],
        ),
    ]
