# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-11-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
